# Generated by scripts/update-tap.sh in Tripstack-Corp/rmatrix. Do not edit by hand.
class Rmatrix < Formula
  desc "Digital rain for modern terminals"
  homepage "https://github.com/Tripstack-Corp/rmatrix"
  version "0.3.2"
  license "MIT"

  # `brew install --HEAD rmatrix` builds main from source. Declared before the
  # platform blocks because `brew audit --strict` requires that ordering.
  head do
    url "https://github.com/Tripstack-Corp/rmatrix.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "2c36ef6c2bdbf7947d3d5c16e73d4865251ed731866493986fa13097908b957b"
    end
    on_intel do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "c68c149838db8b215f2475308f1034fa78e525423fd0ac3e229cd26e22365cba"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "d7e4101a0c5c59927c05eacca48cc7183a9a23fb0e26cc27d50245746f526ce6"
    end
    on_intel do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c842b511d468cc50eb13d44ea529a5f8a547eef00deac85bad0e3f03a58dfbc2"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "rmatrix"
    end
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/rmatrix --version"))
  end
end
