# Generated by scripts/update-tap.sh in Tripstack-Corp/rmatrix. Do not edit by hand.
class Rmatrix < Formula
  desc "Digital rain for modern terminals"
  homepage "https://github.com/Tripstack-Corp/rmatrix"
  version "0.1.0"
  license "MIT"

  # `brew install --HEAD rmatrix` builds main from source. Declared before the
  # platform blocks because `brew audit --strict` requires that ordering.
  head do
    url "https://github.com/Tripstack-Corp/rmatrix.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "bf06d401b7d5ae784f62ee61ff0bd930e36b89daa108bec4d6ce8e4f5a0d29d4"
    end
    on_intel do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "5bd8ce797465156e348e013699f04cae497d3d4a4e840dacd9138c196db1fd61"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "eb26f4cd9703adc054e7ad3934043d2c953e5436f4a26f299aa9af60c4adf6d1"
    end
    on_intel do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b626d9a12101cbd03f0c8eb8f8327b703b138bf752ec21116c61c71d19c0905a"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "rmatrix"
    end
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/rmatrix --version"))
  end
end
