# Generated by scripts/update-tap.sh in Tripstack-Corp/rmatrix. Do not edit by hand.
class Rmatrix < Formula
  desc "Digital rain for modern terminals"
  homepage "https://github.com/Tripstack-Corp/rmatrix"
  version "0.2.0"
  license "MIT"

  # `brew install --HEAD rmatrix` builds main from source. Declared before the
  # platform blocks because `brew audit --strict` requires that ordering.
  head do
    url "https://github.com/Tripstack-Corp/rmatrix.git", branch: "main"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "cf7e030a2dd05862433faf1987489b1e00461f93db57d189cbec02a319f6252d"
    end
    on_intel do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "b585f5a192740a93e1a3e4bc98d46d0b731c1b99d0b2ed8b9a619c3f547845ce"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "98b2be1dafc7350817268150e5f3d5a052d17ea0fed6d3605f223ea9cbdfb859"
    end
    on_intel do
      url "https://github.com/Tripstack-Corp/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "31b1bfbf5003fe519db7c9b278d970a0aa790664d3a45f1231822f525a4dce56"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "rmatrix"
    end
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/rmatrix --version"))
  end
end
